# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: |
          echo "COLOR=#fff" >> $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.COLOR }}"
        
  producer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
          echo "SENTENCE='Dobry ranek'" >> $GITHUB_OUTPUT
    outputs:
      sentence: ${{ steps.sentence_maker.outputs.SENTENCE }}

  consumer:
    needs: [producer]
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: |
          echo ${{ needs.producer.outputs.sentence }}

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > out.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: out
          path: out.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: out
          path: out.txt
          
      - shell: bash
        run: |
          value=`cat out.txt`
          echo $(expr $value \* 9) 
