on:
  workflow_dispatch:
env:
  cat_name: "Puszek"
  WORKFLOW_VAR: "Workflow variable value"

jobs:
  display-variables:
    name: ${{vars.ENVIRONMENT_VAR}}
    environment: test
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job variable value"
    steps:
      - name: Use variables 1
        env:
          STEP_VAR: "Step 1 variable value"
        run: |
          echo "Repository variable : ${{ vars.REPOSITORY_VAR}}"
          echo "Organization variable : ${{ vars.ORGANIZATION_VAR}}"
          echo "Environment variable : ${{ vars.ENVIRONMENT_VAR}}"
          echo "Ala ma kota o nazwie ${{ env.cat_name }}"
          echo "Powinna być zmienna w scopie workflow:${{ env.WORKFLOW_VAR}}"
          echo "Powinna być zmienna w scopie joba:${{ env.JOB_VAR }}"
          echo "Powinna być zmienna w scopie stepu:${{ env.STEP_VAR }}"

      - name: Use variables 2
        env:
          STEP_VAR: "Step 2 variable value"
        run: |
          echo "Ala ma kota o nazwie ${{ env.cat_name }}"
          echo "Powinna być zmienna w scopie workflow:${{ env.WORKFLOW_VAR }}"
          echo "Powinna być zmienna w scopie joba:${{ env.JOB_VAR }}"
          echo "NIE powinna być zmienna w scopie stepu:${{ env.STEP_VAR }}"

      - name: Print all env
        run: |
          env

  display-variables2:
    runs-on: ubuntu-latest
    steps:
      - name: Use variables in display-variables2
        run: |
          echo "Powinna być zmienna w scopie workflow: ${{ env.WORKFLOW_VAR }}"
          echo "NIE powinna być zmienna w scopie joba: ${{ env.JOB_VAR}}"
          echo "NIE powinna być zmienna w scopie stepu: ${{ env.STEP_VAR}}"
